###
# List of methods/modules and their dependencies:
###
modules:
    - name: common
    - name: uri_utils 
      depends: ['common']
    - name: edit_distance 
      depends: ['common']
    - name: anonymization 
      depends: ['common']
#    - name: session
#      depends: ['common']
    - name: connected_components_hawq
      depends: ['common']
    - name: sugar
      depends: ['common']
#    - name: complex
#      depends: ['common']
    - name: stemming
      depends: ['common']
#    - name: sampling
#      depends: ['common']
    - name: complete_linkage
      depends: ['common']
    - name: prediction_metrics
      depends: ['common']
#    - name: plr_placeholder
#      depends: ['common'] 
#  PL/R package disabled until PL/R will be part of Continuous Integration tool.
